!     -*- f90 -*-
!     This file is autogenerated with f2py (version:1.21.1)
!     It contains Fortran 90 wrappers to fortran functions.

      subroutine f2pywrap_nc_fort_sym_positions (tol, super_n, pos, latt&
     &, inv_latt, prim_count, prim_list, frac_pos, pos_keep, n_atoms, bo&
     &nds, n_bonds, exclude, f2py_pos_d0, f2py_pos_d1, f2py_latt_d0, f2p&
     &y_latt_d1, f2py_inv_latt_d0, f2py_inv_latt_d1)
      use nc_fort, only : sym_positions
      real tol
      integer super_n
      integer prim_count
      integer n_atoms
      integer n_bonds
      logical exclude
      integer f2py_pos_d0
      integer f2py_pos_d1
      integer f2py_latt_d0
      integer f2py_latt_d1
      integer f2py_inv_latt_d0
      integer f2py_inv_latt_d1
      real pos(f2py_pos_d0,f2py_pos_d1)
      real latt(f2py_latt_d0,f2py_latt_d1)
      real inv_latt(f2py_inv_latt_d0,f2py_inv_latt_d1)
      integer prim_list(super_n)
      real frac_pos(super_n,3)
      integer pos_keep(super_n)
      real bonds(10000,3)
      call sym_positions(tol, super_n, pos, latt, inv_latt, prim_count, &
     &prim_list, frac_pos, pos_keep, n_atoms, bonds, n_bonds, exclude)
      end subroutine f2pywrap_nc_fort_sym_positions
      subroutine f2pywrap_nc_fort_multmatmul (latt, vec, N, out, f2py_la&
     &tt_d0, f2py_latt_d1, f2py_vec_d0, f2py_vec_d1)
      use nc_fort, only : multmatmul
      integer N
      integer f2py_latt_d0
      integer f2py_latt_d1
      integer f2py_vec_d0
      integer f2py_vec_d1
      real latt(f2py_latt_d0,f2py_latt_d1)
      real vec(f2py_vec_d0,f2py_vec_d1)
      real out(N,3)
      call multmatmul(latt, vec, N, out)
      end subroutine f2pywrap_nc_fort_multmatmul
      subroutine f2pywrap_nc_fort_trans_map (red_list, R, list, L, trans&
     &, N, map, counter, f2py_red_list_d0, f2py_red_list_d1, f2py_list_d&
     &0, f2py_list_d1, f2py_trans_d0, f2py_trans_d1, f2py_trans_d2)
      use nc_fort, only : trans_map
      integer R
      integer L
      integer N
      integer f2py_red_list_d0
      integer f2py_red_list_d1
      integer f2py_list_d0
      integer f2py_list_d1
      integer f2py_trans_d0
      integer f2py_trans_d1
      integer f2py_trans_d2
      real red_list(f2py_red_list_d0,f2py_red_list_d1)
      real list(f2py_list_d0,f2py_list_d1)
      real trans(f2py_trans_d0,f2py_trans_d1,f2py_trans_d2)
      real map(R,N,3,3)
      integer counter(R)
      call trans_map(red_list, R, list, L, trans, N, map, counter)
      end subroutine f2pywrap_nc_fort_trans_map
      subroutine f2pywrap_nc_fort_is_close (array, pos, len_bn, tol, bre&
     &ak_bn, f2py_array_d0, f2py_array_d1, f2py_pos_d0)
      use nc_fort, only : is_close
      integer len_bn
      real tol
      logical break_bn
      integer f2py_array_d0
      integer f2py_array_d1
      integer f2py_pos_d0
      real array(f2py_array_d0,f2py_array_d1)
      real pos(f2py_pos_d0)
      call is_close(array, pos, len_bn, tol, break_bn)
      end subroutine f2pywrap_nc_fort_is_close
      
      subroutine f2pyinitnc_fort(f2pysetupfunc)
      use nc_fort, only : matinv3
      interface 
      subroutine f2pywrap_nc_fort_sym_positions (tol, super_n, pos, latt&
     &, inv_latt, prim_count, prim_list, frac_pos, pos_keep, n_atoms, bo&
     &nds, n_bonds, exclude, f2py_pos_d0, f2py_pos_d1, f2py_latt_d0, f2p&
     &y_latt_d1, f2py_inv_latt_d0, f2py_inv_latt_d1)
      real tol
      integer super_n
      integer prim_count
      integer n_atoms
      integer n_bonds
      logical exclude
      integer f2py_pos_d0
      integer f2py_pos_d1
      integer f2py_latt_d0
      integer f2py_latt_d1
      integer f2py_inv_latt_d0
      integer f2py_inv_latt_d1
      real pos(f2py_pos_d0,f2py_pos_d1)
      real latt(f2py_latt_d0,f2py_latt_d1)
      real inv_latt(f2py_inv_latt_d0,f2py_inv_latt_d1)
      integer prim_list(super_n)
      real frac_pos(super_n,3)
      integer pos_keep(super_n)
      real bonds(10000,3)
      end subroutine f2pywrap_nc_fort_sym_positions 
      subroutine f2pywrap_nc_fort_multmatmul (latt, vec, N, out, f2py_la&
     &tt_d0, f2py_latt_d1, f2py_vec_d0, f2py_vec_d1)
      integer N
      integer f2py_latt_d0
      integer f2py_latt_d1
      integer f2py_vec_d0
      integer f2py_vec_d1
      real latt(f2py_latt_d0,f2py_latt_d1)
      real vec(f2py_vec_d0,f2py_vec_d1)
      real out(N,3)
      end subroutine f2pywrap_nc_fort_multmatmul 
      subroutine f2pywrap_nc_fort_trans_map (red_list, R, list, L, trans&
     &, N, map, counter, f2py_red_list_d0, f2py_red_list_d1, f2py_list_d&
     &0, f2py_list_d1, f2py_trans_d0, f2py_trans_d1, f2py_trans_d2)
      integer R
      integer L
      integer N
      integer f2py_red_list_d0
      integer f2py_red_list_d1
      integer f2py_list_d0
      integer f2py_list_d1
      integer f2py_trans_d0
      integer f2py_trans_d1
      integer f2py_trans_d2
      real red_list(f2py_red_list_d0,f2py_red_list_d1)
      real list(f2py_list_d0,f2py_list_d1)
      real trans(f2py_trans_d0,f2py_trans_d1,f2py_trans_d2)
      real map(R,N,3,3)
      integer counter(R)
      end subroutine f2pywrap_nc_fort_trans_map 
      subroutine f2pywrap_nc_fort_is_close (array, pos, len_bn, tol, bre&
     &ak_bn, f2py_array_d0, f2py_array_d1, f2py_pos_d0)
      integer len_bn
      real tol
      logical break_bn
      integer f2py_array_d0
      integer f2py_array_d1
      integer f2py_pos_d0
      real array(f2py_array_d0,f2py_array_d1)
      real pos(f2py_pos_d0)
      end subroutine f2pywrap_nc_fort_is_close
      end interface
      external f2pysetupfunc
      call f2pysetupfunc(f2pywrap_nc_fort_sym_positions,f2pywrap_nc_fort&
     &_multmatmul,matinv3,f2pywrap_nc_fort_trans_map,f2pywrap_nc_fort_is&
     &_close)
      end subroutine f2pyinitnc_fort


